# Generated by Django 5.2.4 on 2025-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='Is purchased'),
        ),
    ]
