# Generated by Django 5.1.6 on 2025-04-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('price', models.IntegerField(verbose_name='price')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='product name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('product_description', models.TextField(verbose_name='product description')),
                ('product_image', models.ImageField(upload_to='main_photos/products', verbose_name='product image')),
                ('is_available', models.BooleanField(verbose_name='is available')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product photos',
                'verbose_name_plural': 'Product gallery',
            },
        ),
    ]
