# Generated by Django 5.2.4 on 2025-09-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_variations'),
        ('store', '0005_alter_reviewrating_product_alter_reviewrating_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
