# Generated by Django 5.1.6 on 2025-04-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_date_joined_users_is_active_users_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='users',
            name='card_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last entry'),
        ),
    ]
